package service

import (
	"context"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
)

// Provider defines the interface for AI agent CLI providers.
// Each provider knows how to build commands, set up hooks, run one-shots, and clean up.
type Provider interface {
	// ID returns the unique provider identifier (e.g. "claude-code", "codex").
	ID() string

	// BuildCommand constructs the exec.Cmd for launching the agent in a PTY.
	BuildCommand(workDir string, cfg LaunchConfig) *exec.Cmd

	// SetupHooks creates hook artifacts (settings files, scripts) for status tracking.
	// slot distinguishes agent vs reviewer PTYs for the same session.
	// Returns artifacts paths to pass to BuildCommand.
	SetupHooks(sessionID, slot, workDir, callbackURL, instructions string, enableCallbacks bool) (*LaunchArtifacts, error)

	// Cleanup removes all artifacts for a session.
	Cleanup(sessionID string)

	// OneShot executes a single prompt and returns the text response.
	// Used for async review and commit message generation.
	OneShot(ctx context.Context, model, prompt string) (string, error)
}

// LaunchConfig contains the parameters for launching an agent.
type LaunchConfig struct {
	Model        string
	Instructions string
	Artifacts    *LaunchArtifacts
}

// LaunchArtifacts holds provider-specific file paths generated by SetupHooks.
type LaunchArtifacts struct {
	HooksSettingsPath     string
	CodexHome             string
	ModelInstructionsFile string
	ExtraEnv              map[string]string
}

// ProviderRegistry maps provider IDs to implementations.
type ProviderRegistry struct {
	providers map[string]Provider
}

// NewProviderRegistry creates a registry with all known providers.
func NewProviderRegistry() *ProviderRegistry {
	r := &ProviderRegistry{providers: make(map[string]Provider)}
	r.Register(&ClaudeCodeProvider{})
	r.Register(&CodexProvider{})
	return r
}

// Register adds a provider to the registry.
func (r *ProviderRegistry) Register(p Provider) {
	r.providers[p.ID()] = p
}

// Get returns the provider for the given CLI name.
// Falls back to a generic provider for unknown CLIs.
func (r *ProviderRegistry) Get(cliName string) Provider {
	if p, ok := r.providers[cliName]; ok {
		return p
	}
	return &GenericProvider{CLIName: cliName}
}

// CleanupSession removes all provider artifacts for a session.
func (r *ProviderRegistry) CleanupSession(sessionID string) {
	os.RemoveAll(filepath.Join(DataDir(), "hooks", sessionID))
}

// runOneShot is a helper that executes a CLI in one-shot mode via stdin/stdout.
func runOneShot(ctx context.Context, args []string, prompt string) (string, error) {
	cmd := exec.CommandContext(ctx, args[0], args[1:]...)

	stdin, err := cmd.StdinPipe()
	if err != nil {
		return "", fmt.Errorf("oneshot: failed to create stdin pipe: %w", err)
	}

	go func() {
		stdin.Write([]byte(prompt))
		stdin.Close()
	}()

	out, err := cmd.Output()
	if err != nil {
		if exitErr, ok := err.(*exec.ExitError); ok {
			return "", fmt.Errorf("oneshot: command failed: %s: %w", string(exitErr.Stderr), err)
		}
		return "", fmt.Errorf("oneshot: command failed: %w", err)
	}

	return string(out), nil
}

// buildBaseEnv returns the base environment for agent processes.
func buildBaseEnv(extra map[string]string) []string {
	env := append(os.Environ(), "TERM=xterm-256color")
	for k, v := range extra {
		env = append(env, k+"="+v)
	}
	return env
}
